site_name: 浩的个人网站
site_description: 自己的页面
site_author: 郭浩
copyright: 郭浩
theme: readthedocs
site_dir: ../korman.github.io/

pages:
    - 首页: index.md
    - 关于: 
      - 联系方式: about/contact.md
      - 更新日志: about/release-notes.md
    - 文章:
      - 安装vim-go: essays/vim-安装vim-go-打造GOLANG-专用IDE.md